/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoSoRouteImport } from './routes/mo-so'
import { Route as IndexRouteImport } from './routes/index'

const MoSoRoute = MoSoRouteImport.update({
  id: '/mo-so',
  path: '/mo-so',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mo-so': typeof MoSoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mo-so': typeof MoSoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mo-so': typeof MoSoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mo-so'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mo-so'
  id: '__root__' | '/' | '/mo-so'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoSoRoute: typeof MoSoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mo-so': {
      id: '/mo-so'
      path: '/mo-so'
      fullPath: '/mo-so'
      preLoaderRoute: typeof MoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoSoRoute: MoSoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
